name: "raw_audio_cnn_opt"
platform: "onnxruntime_onnx"

input [
  {
    name: "wav_input"
    data_type: TYPE_FP32
    dims: [320000]
  }
]

output [
  {
    name: "raw_output"
    data_type: TYPE_FP32
    dims: [206]
  }
]

max_batch_size: 128
dynamic_batching {
  preferred_batch_size: [32, 64, 128]
  max_queue_delay_microseconds: 100
}
