services:
  birdclef_monolith:
    build:
      context: .
      dockerfile: DockerFile
    container_name: birdclef_allinone
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8000:8000"  # Triton HTTP
      - "8001:8001"  # Triton gRPC
      - "8002:8002"  # Triton metrics
      - "8080:8080"  # FastAPI
      - "8888:8888"  # Jupyter
      - "9090:9090"  # Prometheus
      - "3000:3000"  # Grafana
