version: "3.8"
name: fastapi_test

services:

  fastapi_server:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    container_name: fastapi_server
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./:/workspace
    working_dir: /workspace/fastapi
    ports:
      - "8000:8000"

  jupyter:
    image: quay.io/jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    command: >
      bash -c "pip install numpy && start-notebook.sh --NotebookApp.token=''"
    working_dir: /home/jovyan/work

  flask:
    build:
      context: .
      dockerfile: flask/Dockerfile  # change this based on your actual path
    container_name: flask
    ports:
      - "5000:5000"
    environment:
      - FASTAPI_SERVER_URL=http://fastapi_server:8000
    depends_on:
      - fastapi_server
