global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['localhost:8002']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['localhost:8080']
